apiVersion: v1
kind: Service
metadata:
    name: guyspypipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
    selector:
        app: guyspypipelinesjavascriptdocker
